### ISSUE TITLE
Longer-term TODO List

### ISSUE THREAD

**Issue by LeahPrice** [rcppsmc/rcppsmc#25]
In addition to adding the linear Gaussian example, I have been thinking of doing some of the following minor changes. These should all be relatively quick, besides the ones based on generalizing the examples. Could I please get your thoughts on these @eddelbuettel and @adamjohansen? Feel free to edit this post.

- [ ] Keep track of more log likelihood and log prior calculations in the data annealing linear regression example (to avoid unnecessary extra calculations)
- [ ] Add an example of << ostream operator overloading
- [ ] Allow for proper deep copies of pAdapt and adaptBelong
- [ ] Move the additional parameters for all proposals into parameter objects (?)
- [ ] Add verbose/quiet option for PMMH and output information at every 100 iterations if verbose
- [ ] Add the additional parameters to the history object
- [ ] Generalize the linear regression example
- [ ] Generalize other examples (?)
- [ ] Go back to Hungarian notation (or at least ensure it is consistent)
- [ ] Do we still want to have R wrapper functions for basically every C++ function?
- [ ] Do we still want the folder src/compareGSLtoR in its current location?

I also need to include the updated NEWS and TODO files in the next PR.

**Comment by eddelbuettel** [comment]
Nice list!  But not something we can address in its totality _quickly_ yet we probably need / want a quick turnaround to get something up now as time is winding down.   

I need to double-check but I think RcppSMC currently passes `R CMD check` (as it usually does) so it releasable.  I would put a higher premium on _on getting something to CRAN now_ than on trying to be perfect.  What I learned over the years is that (more, smaller) incremental releases are easier to handle than waiting for the _perfect_ one.  Somehow those never make it out the door.   But hey, just my $0.02.

**Comment by LeahPrice** [comment]
Thanks for this, @eddelbuettel. If @adamjohansen agrees, how do we go about doing the update on CRAN? I can update the version number, NEWS file and TODO. Should the CRAN submission come from Dirk since he is the maintainer?

**Comment by adamjohansen** [comment]
I agree (the list of things to do/think about is a good one, for sure, but there's nothing _essential_ on it as far as I can see and version 0.2.1 can appear whenever we think it ought to so we don't lose anything by making what we have visibly available). Sorry for the slow reply, there have been more pine trees than internet connections in some places. And yes, the submission should come from Dirk.

**Comment by eddelbuettel** [comment]
> I can update the version number, NEWS file and TODO.

The 'maintainer' usually does that.

> Should the CRAN submission come from Dirk since he is the maintainer?

Yes, in fact the submission must match the maintainer name in DESCRIPTION.

I'll go over the package once more today, create a 'n-1' release candidate and once you too had a chance to glance at it we ship.

**Comment by LeahPrice** [comment]
Thanks Adam and Dirk. That sounds great. I'm looking forward to seeing the updated package on CRAN.

**Comment by eddelbuettel** [comment]
I am editing NEWS now.  A few things were missing.  I _definitely_ want you to look over this.  You;ll be up another hew hours?

**Comment by eddelbuettel** [comment]
The release candidate is in [this branch](https://github.com/eddelbuettel/rcppsmc/tree/feature/release_candidate).  Have at it. Checks cleanly for, will try win-builder and r-hub for good measure.  Should be good to go as 0.2.0 with Leah as co-author.

(Which was the price all along but someone was assertive enough early on to edit herself in ;-) )

**Comment by LeahPrice** [comment]
Excellent, thanks Dirk! Yes I can stay up until we've got this sorted.
I added a couple of small comments to the commit. I noticed also that the readme says two additional examples but I should have already changed that to say four.

I did an Rhub check earlier and it took issue with my line endings for the cleanup file. Changing to Unix file endings seemed to fix that on the checks I did. I'm still not entirely sure how it became non-Unix to start with actually.

**Comment by eddelbuettel** [comment]
> I'm still not entirely sure how it became non-Unix to start with actually.

Look into some git tutorials.  There are choices you can set locally (for one repo or all your repos) to have your checkouts convert one-way, both-ways, not-at-all, ...   I have no idea what to recommend as I avoid Windows for development.   You want to end up somewhere where your actions have the least possible side-effects.  That may be "automatic changes in and out".

**Comment by eddelbuettel** [comment]
So for editing NEWS.Rd:  Can you maybe 
- just fetch the file, 
- save it is `NEWS.Rd.orig`, 
- make edits in your local `NEWS.Rd` and then 
- paste here in a block with thre backticks and `diff` 
- the output of `diff -u NEWS.Rd.orig NEWS.Rd`

**Comment by LeahPrice** [comment]
Sorry it looks like you've already updated NEWS, so do you mean the README? I've got an updated readme and also TODO, but just figuring out how to get the plain text version of the diff rather than pretty version.

**Comment by eddelbuettel** [comment]
Any file you want changed, it helps me if you are as precise as possible and show changes against current file.  As a `diff` output.

I actually did just that over on the other comment thread we have going.

I think we're mostly good.  We can wait for Adam, but worst case I can toss it at CRAN.  If you want changes, detail them please.   

And of course we can also wait or are we up against a hard deadline?  GSoC does not _really_ care as the work was done (which matters) and upload now, this week, next week, ... is all good to them AFAIK.

**Comment by LeahPrice** [comment]
Yeah I can see how a diff file is helpful but it might take me some time to figure out how to get a plain text version of the diff file. I'm sure I could do it with time, but perhaps [this diff link](https://github.com/eddelbuettel/rcppsmc/compare/feature/release_candidate...LeahPrice:test) will be okay?

It sounds like we're not up against a hard deadline for GSoC. In about 20 hours from now I'll be on a 24 hour flight so I won't be able to access emails during that time.

**Comment by eddelbuettel** [comment]
I just committed the NEWS.Rd in question so you have a more definite copy to work with [eg via this link](https://raw.githubusercontent.com/eddelbuettel/rcppsmc/feature/release_candidate/inst/NEWS.Rd). 

I'll refrain from making further changes for a bit.  Off for a run, belatedly...

**Comment by LeahPrice** [comment]
Thanks Dirk. I'm happy with the changes you've made to the NEWS file. It's nice and succinct and it covers all of the main issue tickets and pull requests.

I do have a couple of changes for the README and TODO files though, which I've included [here](https://github.com/eddelbuettel/rcppsmc/compare/feature/release_candidate...LeahPrice:test) (diff files shown at link).

Enjoy your run! I may head off to bed soon and check Github again first thing tomorrow. It's getting pretty late here now (1.30am)

**Comment by eddelbuettel** [comment]
Ah yes, point taken re the README.md.  Will do.

The TODO can wait.

**Comment by adamjohansen** [comment]
I agree (the list of things to do/think about is a good one, for sure, but there's nothing _essential_ on it as far as I can see and version 0.2.1 can appear whenever we think it ought to so we don't lose anything by making what we have visibly available). Sorry for the slow reply, there have been more pine trees than internet connections in some places. And yes, the submission should come from Dirk.

**Comment by eddelbuettel** [comment]
Will release 0.2.0.  So how about if we retitle this to 'Longer-term TODO List' or something like it?

**Comment by eddelbuettel** [comment]
I think closing this ticket because one item was ticked off (thanks, @binxiangni ) was not intended.

Shall we reopen?

**Comment by adamjohansen** [comment]
I think so, there's still stuff on that list we'd ideally like to do in the fullness of time -- isn't there @LeahPrice ?

Also, perhaps we should add resolving the memory deallocation issue with copied samplers to the list if I wasn't missing anything with the comment on the _copy function earlier.

**Comment by LeahPrice** [comment]
Oops! Thanks Dirk! I didn't realise I'd closed this ticket. I've updated the list to include dealing with the memory deallocation issue.

**Comment by tibi77** [comment]
I think tat the number 2 on the list is done. Please update!

**Comment by tibi77** [comment]
1) For the verbose and quite output which info should be outputted? The ones that I find relevant or you have something specific in mind?  [point 5]
2) Also the iteration should stop and wait for user input or it should keep going and write the output in the terminal? 
3) I have some questions about the format of the output.

**Comment by LeahPrice** [comment]
Are you familiar with Markov chain Monte Carlo? I will assume below that you are - if not it is worth Googling and/or asking more.

This example is doing Markov chain Monte Carlo (MCMC) where the likelihood is estimated using particle filtering. At each MCMC iteration, a set of parameters for the model are proposed and you do a particle filtering run with those parameters to get the normalizing constant. The result from `Sampler.GetLogNCPath();` gives you the log of the estimated likelihood.

The default for this example is `particles = 5000` and MCMC `iterations = 100,000`, so that means we are essentially doing 100,000 particle filtering runs in a row with slightly different configurations on each run. As you can imagine, this can take a long time!

In my opinion, the point of outputting the results is just to see how the method is progressing. You might want to print the MCMC iteration number (`i`) every 100 iterations or so and perhaps also at the same time the acceptance probability (we are estimating the likelihood so we sometimes overestimate it and we can get stuck without making any acceptances for a long time). 

There might also be some value in outputting the current values of `theta_prop` and the associated log likelihood and log prior values (`loglike_prop` and `logprior_prop`). To me that seems less valuable unless you're going to output the results at every iteration.

**Comment by LeahPrice** [comment]
Just to make that more clear, my opinion is to just go with outputting the iteration number and acceptance probability every 100 iterations.

**Comment by adamjohansen** [comment]
It might well be sensible to include the log target density in the output as the behaviour of this quantity gives some indication of whether the chain is still in a transient regime or has reached a _typical set_ yet.

**Comment by tibi77** [comment]
I think the output of the theta_prop, loglike_prop and logprior_prop will be tedious and also hard for the user to read. From what I can understand from the code the acceptance probability is kept in the MH_ratio. Is that so?
Also wouldn't you think that it will be a better idea to document what the variable names mean?

**Comment by adamjohansen** [comment]
With verbose output there's a trade-off between readability and actually providing some additional information; I'd think a user specifically asking for verbosity would be willing to see a few different numbers every hundred iterations. Someone with a bit of practical experience from MCMC will get much more from having at least some of this information -- which will fit on a single console line.

The minimum of 1 ad MH_ratio is the acceptance probablity in a particular iteration,  but ti would be more usual to show the running average of this quantity, I think, unless Leah particularly wants to see the instantaneous value. The running average is useful for diagnostic purposes (happy to elaborate or point to literature if you like).

Documentation is somewhat inadequate for the entire package at present and resolving that is a long term goal but one which isn't top of the priority list. Doxygen was used for the C++ library this evolved from and we have toyed with the idea of using doxygen/roxygen to provide proper code documentation but haven't got around to doing so. Comments in the code broadly consistent with following that path in the future would certainly be valuable.

**Comment by LeahPrice** [comment]
Actually yeah that's another good reason to include it.

By acceptance probability, I meant the proportion of accepted moves so far. So you would keep track of the number of accepted moves.

**Comment by adamjohansen** [comment]
Did you mean to close this, @LeahPrice?

**Comment by LeahPrice** [comment]
No I didn't - wow I thought I had stupidly pressed comment instead of cancel but looks like I pressed close and comment.

I'm going to head home now before I embarrass myself more haha

**Comment by tibi77** [comment]
@adamjohansen if you want I can implement grades of verboseness. I think there are some linux commands that have that implemented.

**Comment by adamjohansen** [comment]
There are, but I wouldn't over-complicate this myself... I think it was @LeahPrice that suggested adding a bit more output and IIRC the logic is just that it's good for commands that can take a very long time to execute to give a bit of online feedback so that the user can see that (a) something is happening and (b) that it isn't obviously failing to work.
